//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data;


namespace Jelineksoft.Entity
{
    public abstract class ProviderBase
    {

        public ProviderBase()
        {
        }

        public String ConnectionString { get; set; }

        private Int32 _commandTimeout = 35;

        public Int32 CommandTimeout
        {
            get { return _commandTimeout; }
            set { _commandTimeout = value; }
        }

        public abstract ProviderBase GetProvider();

        public abstract IDbConnection Connect();

        public abstract void Disconnect();

        public abstract void ParametersRemoveAll();

        public abstract void AddWhereParameter(String _columnName, String _tableName, Object _value,
            PropertyCompareOperatorEnum _propertyCompare, WhereMergeOperatorEnum _whereMergeOperator);

        public abstract void AddWhereParameterIN(String _columnName, String _tableName, Array _values,
            WhereMergeOperatorEnum _whereMergeOperator, Boolean NotIn);

        public abstract void AddWhereString(String _whereString);

        public abstract void AddWhereParenthesisStart();

        public abstract void AddWhereParenthesisEnd();

        public abstract void AddLimit(Int32 count);

        public abstract void AddDistinct();

        public abstract void AddOrderBy(string _columnName, string _tableName, Boolean _asc);

        public abstract void AddOrderBy(string _string);

        public abstract System.Data.IDataReader CreateSqlSelect();

        public abstract void CreateSqlUpDate(String tableName);

        public abstract Object CreateSqlInsert(string _tableName, bool autoincr);
        public abstract void CreateDelete(string _idColumnName, object _idValue, string _tableName);

        public abstract void CreateDelete(string _tableName);

        public abstract void ResetProvider();

        public abstract void AddColumnToSelect(String _columnName, String _tableName);

        public abstract void AddColumnToSelect(String _columnName);
        public abstract void AddCustomToSelect(string txt);

        public abstract void AddColumnToUpdate(string _name, object value);
        public abstract void AddColumnToInsert(string _name, object value);
        public abstract void AddFrom(String _tableName, String _tableNameShortcut);

        public abstract void AddJoin(JoinTypeEnum _joinType, String _joinTableName, String _joinTableNameShortcut, String _tableNameLeft, String _columnNameLeft, String _tableNameRight, String _columnNameRight);

        public abstract Object ExecuteScalar(String _sql);

        public abstract Object ExecuteScalar(String _sql, Boolean _isStoredProcedure);

        public abstract System.Data.IDataReader ExecuteReader(String _sql);

        public abstract System.Data.IDataReader ExecuteReader(String _sql, Boolean _isStoredProcedure);

        public abstract void AddGroupBy(String _tableName, String _columnName);

        public abstract String AddAggregationFce(AggregationFunctionsEnum _fceType,String _tableName, String _columnName);

        public abstract String AddAggregationFce(AggregationFunctionsEnum _fceType, String _mathFce);

        public abstract String AddMathFce(String _tableNameLeft, String _columnNameLeft,String _tableNameRight, String _columnNameRight, MathOperatorEnum _operator, Boolean _addParenthises);

        public abstract String AddMathFce(String _columnNameLeft, String _columnNameRight, MathOperatorEnum _operator, Boolean _addParenthises);

        public abstract String AddMathFce(String xText, Boolean _addParenthesis);

        public abstract System.Data.IDataReader RunProcedure(String _procedureName, System.Collections.Generic.List<System.Data.IDataParameter> _parameters);

        public abstract System.Data.IDataParameter CreateParameter();

        public abstract object ReaderReturnNetType(object value);

    }
}
